# -*- coding: utf-8 -*-
"""sorting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAUYwztcTgafd0x69ph9PZVKw_X0hgTd
"""



import numpy as np

# Generate a 1000-element random integer array with values between 0 and 100
random_int_array = np.random.randint(0, 101, size=1000)

# Print the first 10 elements to verify the array generation
print("First 10 elements of the random integer array:")
print(random_int_array[:10])

import time
import matplotlib.pyplot as plt
import numpy as np

# Define a list of input lengths for benchmarking (from 500 to 10000 in steps of 500)
input_lengths = [i * 500 for i in range(1, 21)]
# List to store the runtime for each input length
runtimes = []

print("Benchmarking qsort...")
# Iterate through each input length to benchmark the qsort function
for length in input_lengths:
    # Generate a random integer array of the current length for testing
    test_array = np.random.randint(0, 1000, size=length).tolist()

    # Record the start time before calling qsort
    start_time = time.time()
    # Call the qsort function
    qsort(test_array)
    # Record the end time after qsort completes
    end_time = time.time()

    # Calculate the runtime and add it to the runtimes list
    runtimes.append(end_time - start_time)
    # Print the length and its corresponding runtime
    print(f"Length: {length}, Runtime: {end_time - start_time:.6f} seconds")

print("Benchmarking complete.")

# Create a figure for the plot with a specified size
plt.figure(figsize=(10, 6))
# Plot the runtimes against the input lengths
plt.plot(input_lengths, runtimes, marker='o', linestyle='-', color='b')
# Add a title to the plot
plt.title('qsort Runtime vs. Input Length')
# Add a label for the x-axis
plt.xlabel('Input Length')
# Add a label for the y-axis
plt.ylabel('Runtime (seconds)')
# Add a grid to the plot for better readability
plt.grid(True)
# Display the plot
plt.show()

nums = random_int_array.tolist()
print(nums)

# Define the qsort (quicksort) function recursively
def qsort(nums):
  # Base case: if the list has 0 or 1 element, it's already sorted
  if len(nums) <= 1:
    return nums

  # Choose the first element as the pivot
  pivot = nums[0]
  # Create a sublist of elements less than or equal to the pivot
  left = [num for num in nums[1:] if num <= pivot]
  # Create a sublist of elements greater than the pivot
  right = [num for num in nums[1:] if num > pivot]

  # Recursively sort the left and right sublists and combine them with the pivot
  return qsort(left) + [pivot] + qsort(right)

print(qsort(nums))

# Define a function to test if an array is sorted in ascending order
def sort_tester(nums):
  # Iterate through the array up to the second-to-last element
  for i in range(len(nums)-1):
    # If any element is greater than the next element, the array is not sorted
    if nums[i] > nums[i+1]:
      return False
  # If the loop completes, the array is sorted
  return True

print(sort_tester(qsort(nums)))

print(sort_tester(nums))

import numpy as np
import matplotlib.pyplot as plt

# Calculate n*log(n) for each input length to compare with O(n log n) complexity
n_log_n_values = [n * np.log(n) for n in input_lengths]

# Create a figure for the plot with a specified size
plt.figure(figsize=(10, 6))
# Plot the observed runtimes against the calculated n*log(n) values
plt.plot(n_log_n_values, runtimes, 'o', color='red', label='Observed Runtimes vs. n log n')
# Add a title to the plot
plt.title('qsort Runtime vs. n log n')
# Add a label for the x-axis
plt.xlabel('n * log(n)')
# Add a label for the y-axis
plt.ylabel('Runtime (seconds)')
# Add a grid to the plot for better readability
plt.grid(True)

# Optional: Add a linear regression line to visualize linearity
# This helps to visually confirm if the relationship is linear

# Fit a linear model (degree 1 polynomial) to the n_log_n_values and runtimes
p = np.polyfit(n_log_n_values, runtimes, 1)
# Plot the linear regression line
plt.plot(n_log_n_values, np.polyval(p, n_log_n_values), '-', color='blue', label='Linear Fit')

# Display the legend to differentiate plotted lines
plt.legend()
# Display the plot
plt.show()